-- Equipa 0.2.9: cadastro rápido sem perder QR, integridade e histórico.
-- Esta migration já foi aplicada ao projeto oxcfbsrukzfnzkivatsn.
-- Reutiliza o registro transacional existente. Não altera estruturas antigas.
create or replace function public.equipa_quick_register_equipment(
  p_code text,
  p_model text,
  p_action_id uuid,
  p_location_text text default null,
  p_asset_tag text default null,
  p_brand text default null
) returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select (
    private.register_equipment_batch_internal(
      jsonb_build_array(
        jsonb_build_object(
          'code', nullif(btrim(p_code),''),
          'model', nullif(btrim(p_model),''),
          'brand', coalesce(nullif(btrim(p_brand),''),'Não informado'),
          'location_text', nullif(btrim(p_location_text),''),
          'asset_tag', nullif(btrim(p_asset_tag),'')
        )
      ),
      p_action_id
    )->0
  );
$$;
revoke all on function public.equipa_quick_register_equipment(text,text,uuid,text,text,text)
  from public, anon;
grant execute on function public.equipa_quick_register_equipment(text,text,uuid,text,text,text)
  to authenticated;
comment on function public.equipa_quick_register_equipment(text,text,uuid,text,text,text)
 is 'Single-request fast enrollment: code and model required; QR and UUID generated by protected transactional batch function; no personal data added.';
notify pgrst,'reload schema';
